spring:
  profiles:
    active: dev
  rabbitmq:
    host: ${RABBIT_MQ_HOST:182.254.208.28}
    port: ${RABBIT_MQ_PORT:15672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
#  config:  classpath:log4j2-spring.xml #默认文件名，可不配置